# Generated by Django 3.1.7 on 2021-03-08 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.TextField(choices=[('published', 'published'), ('not published', 'not published')], default=''),
        ),
    ]
